"""
Curated list of global AI thought leaders tracked by AI情报官.
Categories: scientists, founders, opinion_leaders, podcasts
"""

INFLUENCERS = [
    # ─────────────── AI Scientists & Researchers ───────────────
    {
        "id": "karpathy",
        "name": "Andrej Karpathy",
        "handle": "karpathy",
        "twitter_id": "33836629",
        "category": "scientist",
        "category_zh": "科学家",
        "title": "Former Tesla AI / OpenAI",
        "title_zh": "前Tesla AI / OpenAI",
        "avatar": "https://pbs.twimg.com/profile_images/1296020950547021824/9DsOJMtC_400x400.jpg",
        "bio": "AI researcher, educator, and builder.",
    },
    {
        "id": "ylecun",
        "name": "Yann LeCun",
        "handle": "ylecun",
        "twitter_id": "3052585",
        "category": "scientist",
        "category_zh": "科学家",
        "title": "Meta Chief AI Scientist",
        "title_zh": "Meta首席AI科学家",
        "avatar": "https://pbs.twimg.com/profile_images/1483577865056702469/rWA-3_T7_400x400.jpg",
        "bio": "Chief AI Scientist at Meta, Turing Award winner.",
    },
    {
        "id": "drfeifei",
        "name": "Fei-Fei Li",
        "handle": "drfeifei",
        "twitter_id": "17919972",
        "category": "scientist",
        "category_zh": "科学家",
        "title": "Stanford HAI / World Labs",
        "title_zh": "斯坦福HAI / World Labs",
        "avatar": "https://pbs.twimg.com/profile_images/1488580490843865088/UR9nKiPN_400x400.jpg",
        "bio": "ImageNet creator, Stanford professor, World Labs founder.",
    },
    {
        "id": "demishassabis",
        "name": "Demis Hassabis",
        "handle": "demishassabis",
        "twitter_id": "92650456",
        "category": "scientist",
        "category_zh": "科学家",
        "title": "Google DeepMind CEO",
        "title_zh": "Google DeepMind CEO",
        "avatar": "https://pbs.twimg.com/profile_images/1234936553895845888/5kWjXpIZ_400x400.jpg",
        "bio": "Co-founder and CEO of Google DeepMind, Nobel Prize in Chemistry 2024.",
    },
    {
        "id": "ilyasut",
        "name": "Ilya Sutskever",
        "handle": "ilyasut",
        "twitter_id": "191590819",
        "category": "scientist",
        "category_zh": "科学家",
        "title": "SSI Co-founder",
        "title_zh": "SSI联合创始人",
        "avatar": "https://pbs.twimg.com/profile_images/1512594804965310464/oGxEJYpP_400x400.jpg",
        "bio": "Co-founder of SSI, former OpenAI Chief Scientist.",
    },
    # ─────────────── AI Company Founders & CEOs ───────────────
    {
        "id": "sama",
        "name": "Sam Altman",
        "handle": "sama",
        "twitter_id": "83481901",
        "category": "founder",
        "category_zh": "创始人",
        "title": "OpenAI CEO",
        "title_zh": "OpenAI CEO",
        "avatar": "https://pbs.twimg.com/profile_images/804990434455887872/BG0Xh7Oa_400x400.jpg",
        "bio": "CEO of OpenAI.",
    },
    {
        "id": "dario_amodei",
        "name": "Dario Amodei",
        "handle": "dario_amodei",
        "twitter_id": "1089776030",
        "category": "founder",
        "category_zh": "创始人",
        "title": "Anthropic CEO",
        "title_zh": "Anthropic CEO",
        "avatar": "https://pbs.twimg.com/profile_images/1567145701893283845/Oe1OFTuU_400x400.jpg",
        "bio": "CEO and Co-founder of Anthropic.",
    },
    {
        "id": "danielaamodei",
        "name": "Daniela Amodei",
        "handle": "danielaamodei",
        "twitter_id": "1059657847",
        "category": "founder",
        "category_zh": "创始人",
        "title": "Anthropic President",
        "title_zh": "Anthropic总裁",
        "avatar": "https://pbs.twimg.com/profile_images/1581018317095247872/s5EUTaXR_400x400.jpg",
        "bio": "President and Co-founder of Anthropic.",
    },
    {
        "id": "gdb",
        "name": "Greg Brockman",
        "handle": "gdb",
        "twitter_id": "30892908",
        "category": "founder",
        "category_zh": "创始人",
        "title": "OpenAI Co-founder",
        "title_zh": "OpenAI联合创始人",
        "avatar": "https://pbs.twimg.com/profile_images/991800434219851776/mJEoNVvM_400x400.jpg",
        "bio": "Co-founder and former President of OpenAI.",
    },
    {
        "id": "mustafasuleyman",
        "name": "Mustafa Suleyman",
        "handle": "mustafasuleyman",
        "twitter_id": "236447317",
        "category": "founder",
        "category_zh": "创始人",
        "title": "Microsoft AI CEO",
        "title_zh": "微软AI CEO",
        "avatar": "https://pbs.twimg.com/profile_images/1580527498064609280/cFQ0gGnR_400x400.jpg",
        "bio": "CEO of Microsoft AI, Co-founder of DeepMind.",
    },
    {
        "id": "arthurmensch",
        "name": "Arthur Mensch",
        "handle": "arthurmensch",
        "twitter_id": "123456789",
        "category": "founder",
        "category_zh": "创始人",
        "title": "Mistral AI CEO",
        "title_zh": "Mistral AI CEO",
        "avatar": "https://pbs.twimg.com/profile_images/default.jpg",
        "bio": "CEO and Co-founder of Mistral AI.",
    },
    {
        "id": "aidan_gomez",
        "name": "Aidan Gomez",
        "handle": "aidan_gomez",
        "twitter_id": "987654321",
        "category": "founder",
        "category_zh": "创始人",
        "title": "Cohere CEO",
        "title_zh": "Cohere CEO",
        "avatar": "https://pbs.twimg.com/profile_images/default.jpg",
        "bio": "CEO and Co-founder of Cohere.",
    },
    # ─────────────── AI Opinion Leaders ───────────────
    {
        "id": "emollick",
        "name": "Ethan Mollick",
        "handle": "emollick",
        "twitter_id": "14289516",
        "category": "opinion_leader",
        "category_zh": "意见领袖",
        "title": "Wharton Professor",
        "title_zh": "沃顿商学院教授",
        "avatar": "https://pbs.twimg.com/profile_images/1608960895628083201/vIp-RKhk_400x400.jpg",
        "bio": "Wharton professor researching AI and work.",
    },
    {
        "id": "garymarcus",
        "name": "Gary Marcus",
        "handle": "garymarcus",
        "twitter_id": "45885378",
        "category": "opinion_leader",
        "category_zh": "意见领袖",
        "title": "AI Researcher & Author",
        "title_zh": "AI研究员和作家",
        "avatar": "https://pbs.twimg.com/profile_images/1586088408024805376/8JfNnrN2_400x400.jpg",
        "bio": "Scientist, author, entrepreneur, and AI critic.",
    },
    {
        "id": "benedictevans",
        "name": "Benedict Evans",
        "handle": "benedictevans",
        "twitter_id": "71001234",
        "category": "opinion_leader",
        "category_zh": "意见领袖",
        "title": "Tech Analyst",
        "title_zh": "科技分析师",
        "avatar": "https://pbs.twimg.com/profile_images/1223578349975822337/NSaM7aWG_400x400.jpg",
        "bio": "Independent tech analyst.",
    },
    {
        "id": "paulg",
        "name": "Paul Graham",
        "handle": "paulg",
        "twitter_id": "28815170",
        "category": "opinion_leader",
        "category_zh": "意见领袖",
        "title": "YCombinator Co-founder",
        "title_zh": "YC联合创始人",
        "avatar": "https://pbs.twimg.com/profile_images/1824002576/pg-railsconf_400x400.jpg",
        "bio": "Co-founder of Y Combinator.",
    },
    {
        "id": "karpathy2",
        "name": "Nathan Lambert",
        "handle": "natolambert",
        "twitter_id": "1234567890",
        "category": "opinion_leader",
        "category_zh": "意见领袖",
        "title": "Allen AI / RLHF Expert",
        "title_zh": "Allen AI / RLHF专家",
        "avatar": "https://pbs.twimg.com/profile_images/default.jpg",
        "bio": "AI alignment researcher at Allen Institute for AI.",
    },
    {
        "id": "rasbt",
        "name": "Sebastian Raschka",
        "handle": "rasbt",
        "twitter_id": "2345678901",
        "category": "opinion_leader",
        "category_zh": "意见领袖",
        "title": "ML Educator & Author",
        "title_zh": "机器学习教育者",
        "avatar": "https://pbs.twimg.com/profile_images/default.jpg",
        "bio": "Machine Learning Educator, Author of 'Build an LLM from Scratch'.",
    },
    # ─────────────── AI Podcasts & Media ───────────────
    {
        "id": "lexfridman",
        "name": "Lex Fridman",
        "handle": "lexfridman",
        "twitter_id": "27576527",
        "category": "podcast",
        "category_zh": "播客",
        "title": "Lex Fridman Podcast",
        "title_zh": "Lex Fridman播客",
        "avatar": "https://pbs.twimg.com/profile_images/1743897430849880067/k78SFgJH_400x400.jpg",
        "bio": "AI researcher and host of the Lex Fridman Podcast.",
    },
    {
        "id": "dwarkesh_sp",
        "name": "Dwarkesh Patel",
        "handle": "dwarkesh_sp",
        "twitter_id": "1345678901",
        "category": "podcast",
        "category_zh": "播客",
        "title": "Dwarkesh Podcast",
        "title_zh": "Dwarkesh播客",
        "avatar": "https://pbs.twimg.com/profile_images/1640078558659891201/nrBlVQcU_400x400.jpg",
        "bio": "Host of the Dwarkesh Podcast, interviewing top AI researchers.",
    },
    {
        "id": "saranormous",
        "name": "Sarah Guo",
        "handle": "saranormous",
        "twitter_id": "22654321",
        "category": "podcast",
        "category_zh": "播客",
        "title": "No Priors Podcast",
        "title_zh": "No Priors播客",
        "avatar": "https://pbs.twimg.com/profile_images/1535375494396022789/RUV2IUDE_400x400.jpg",
        "bio": "VC at Conviction, host of No Priors podcast.",
    },
    {
        "id": "timnitgebru",
        "name": "Timnit Gebru",
        "handle": "timnitgebru",
        "twitter_id": "79462430",
        "category": "opinion_leader",
        "category_zh": "意见领袖",
        "title": "DAIR Institute Founder",
        "title_zh": "DAIR研究院创始人",
        "avatar": "https://pbs.twimg.com/profile_images/1494752900/tgebrual_400x400.jpg",
        "bio": "Founder of DAIR Institute, AI ethics researcher.",
    },
]

CATEGORIES = {
    "all": {"label": "全部", "en": "All"},
    "scientist": {"label": "科学家", "en": "Scientists"},
    "founder": {"label": "创始人", "en": "Founders"},
    "opinion_leader": {"label": "意见领袖", "en": "Opinion Leaders"},
    "podcast": {"label": "播客", "en": "Podcasts"},
}

def get_influencer_by_id(influencer_id: str) -> dict | None:
    return next((i for i in INFLUENCERS if i["id"] == influencer_id), None)

def get_influencers_by_category(category: str) -> list:
    if category == "all":
        return INFLUENCERS
    return [i for i in INFLUENCERS if i["category"] == category]
